### ISSUE TITLE
This happened?

### ISSUE THREAD

**Issue by karai17** [Fankserver/atom-firepad#10]
```
c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\lib\firebase-node.js:44
Hide Stack Trace
Error: sendOperation() called with invalid operation.
  at assert (c:\Users\Karai\.atom\packages\firepad\lib\firepad-lib.js:1645:13)
  at FirebaseAdapter.firepad.FirebaseAdapter.FirebaseAdapter.sendOperation (c:\Users\Karai\.atom\packages\firepad\lib\firepad-lib.js:1403:5)
  at EditorClient.firepad.EditorClient.EditorClient.sendOperation (c:\Users\Karai\.atom\packages\firepad\lib\firepad-lib.js:2358:24)
  at AwaitingWithBuffer.firepad.Client.AwaitingWithBuffer.serverAck (c:\Users\Karai\.atom\packages\firepad\lib\firepad-lib.js:2187:12)
  at EditorClient.firepad.Client.Client.serverAck (c:\Users\Karai\.atom\packages\firepad\lib\firepad-lib.js:2030:30)
  at EditorClient.serverAdapter.registerCallbacks.ack (c:\Users\Karai\.atom\packages\firepad\lib\firepad-lib.js:2273:31)
  at FirebaseAdapter.clazz.trigger (c:\Users\Karai\.atom\packages\firepad\lib\firepad-lib.js:38:29)
  at FirebaseAdapter.firepad.FirebaseAdapter.FirebaseAdapter.handlePendingReceivedRevisions_ (c:\Users\Karai\.atom\packages\firepad\lib\firepad-lib.js:1570:18)
  at c:\Users\Karai\.atom\packages\firepad\lib\firepad-lib.js:1510:16
  at c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\lib\firebase-node.js:94:979
  at ac (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\lib\firebase-node.js:44:20)
  at Td (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\lib\firebase-node.js:94:965)
  at Rd.Eb (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\lib\firebase-node.js:94:908)
  at Ud.Eb (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\lib\firebase-node.js:95:417)
  at c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\lib\firebase-node.js:110:406
  at c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\lib\firebase-node.js:62:1194
  at Wb (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\lib\firebase-node.js:58:222)
  at R (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\lib\firebase-node.js:62:1171)
  at c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\lib\firebase-node.js:110:386
  at Ra (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\lib\firebase-node.js:29:154)
  at ue (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\lib\firebase-node.js:110:358)
  at W (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\lib\firebase-node.js:110:317)
  at Ae.h.cc (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\lib\firebase-node.js:118:462)
  at md.h.bc (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\lib\firebase-node.js:86:287)
  at ad.bc (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\lib\firebase-node.js:77:364)
  at Q.Od (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\lib\firebase-node.js:75:280)
  at Ec (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\lib\firebase-node.js:61:234)
  at [object Object].W.onmessage (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\lib\firebase-node.js:60:111)
  at [object Object].EventTarget.dispatchEvent (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\node_modules\faye-websocket\lib\faye\websocket\api\event_target.js:22:30)
  at [object Object].instance._receiveMessage (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\node_modules\faye-websocket\lib\faye\websocket\api.js:134:10)
  at [object Object].<anonymous> (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\node_modules\faye-websocket\lib\faye\websocket\api.js:34:49)
  at [object Object].emit (events.js:129:20)
  at [object Object].<anonymous> (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\node_modules\faye-websocket\node_modules\websocket-driver\lib\websocket\driver\hybi.js:444:14)
  at [object Object].Pipeline.processIncomingMessage (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\node_modules\faye-websocket\node_modules\websocket-driver\node_modules\websocket-extensions\lib\pipeline.js:24:14)
  at [object Object].instance.processIncomingMessage (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\node_modules\faye-websocket\node_modules\websocket-driver\node_modules\websocket-extensions\lib\websocket_extensions.js:133:20)
  at [object Object].instance._emitMessage (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\node_modules\faye-websocket\node_modules\websocket-driver\lib\websocket\driver\hybi.js:435:22)
  at [object Object].instance._emitFrame (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\node_modules\faye-websocket\node_modules\websocket-driver\lib\websocket\driver\hybi.js:398:19)
  at [object Object].instance.parse (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\node_modules\faye-websocket\node_modules\websocket-driver\lib\websocket\driver\hybi.js:144:18)
  at [object Object].instance.parse (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\node_modules\faye-websocket\node_modules\websocket-driver\lib\websocket\driver\client.js:56:58)
  at [object Object].IO.write (c:\Users\Karai\.atom\packages\firepad\node_modules\firebase\node_modules\faye-websocket\node_modules\websocket-driver\lib\websocket\streams.js:80:16)
  at TLSSocket.ondata (_stream_readable.js:539:20)
  at TLSSocket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:161:16)
  at TLSSocket.Readable.push (_stream_readable.js:125:10)
  at TCP.onread (net.js:522:20)
```

**Comment by Fank** [comment]
How often does this appear?
Can you add steps how to reproduce?
