### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispose' of undefined

### ISSUE THREAD

**Issue by despairblue** [Fankserver/atom-firepad#13]
[Enter steps to reproduce below:]

unsharing a not shared buffer

**Atom Version**: 0.200.0
**System**: linux 3.14.39-1-lts
**Thrown From**: [firepad](https://github.com/firebase/atom-firepad) package, v0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At /home/despairblue/.atom/packages/firepad/lib/firepad.coffee:69

TypeError: Cannot read property 'dispose' of undefined
  at FirepadView.module.exports.FirepadView.unshare (/home/despairblue/.atom/packages/firepad/lib/firepad.coffee:69:9)
  at atom-workspace.<anonymous> (/home/despairblue/.atom/packages/firepad/lib/firepad.coffee:29:55)
  at atom-workspace.handler (/usr/share/atom/resources/app.asar/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -0:06.4.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
     -0:04.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.3.0 firepad:unshare (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "welcome",
      "metrics",
      "autocomplete",
      "incremental-search",
      "Tern",
      "grunt-runner",
      "tree-view-open-files",
      "tree-view-breadcrumb",
      "atomatigit",
      "themed-settings",
      "linter-scspell",
      "filetype-color",
      "atom-pair",
      "linter-eslint",
      "es-navigation",
      "autocomplete",
      "tab-smart-sort",
      "starred-package-installer",
      "zentabs",
      "linter-jshint",
      "block-cursor",
      "test-status",
      "minimap",
      "minimap-color-highlight",
      "minimap-find-and-replace",
      "minimap-git-diff",
      "minimap-highlight-selected",
      "travis-ci-status",
      "pane-layout-plus",
      "symbols-tree-view",
      "package-cop",
      "navigate"
    ],
    "projectHome": "/home/despairblue/vcs/git/",
    "destroyEmptyPanes": false,
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-alignment, v0.12.1
atom-color-highlight, v3.0.9
atom-ternjs, v0.6.0
atom-zeal, v0.1.0
autocomplete-emojis, v2.2.2
autocomplete-paths, v1.0.2
block-travel, v1.0.2
bug-report, v0.7.0
color-picker, v1.7.0
compare-files, v0.4.1
docblockr, v0.7.1
editorconfig, v1.0.0
file-icons, v1.5.5
firepad, v0.3.1
git-log, v0.3.0
go-plus, v3.3.11
grammar-token-limit, v0.1.1
highlight-selected, v0.9.3
indentation-indicator, v0.5.1
javascript-snippets, v1.0.0
keybinding-cheatsheet, v0.0.9
language-dockerfile, v0.1.0
language-dot, v1.6.0
language-fish-shell, v1.0.2
language-haskell, v1.0.0
language-javascript-better, v1.5.0
language-latex, v0.6.1
language-nimrod, v0.1.0
language-puppet, v0.12.0
language-tss, v0.1.0
latex, v0.23.4
linter, v0.12.4
linter-coffeelint, v0.2.3
linter-htmlhint, v0.0.15
linter-js-standard, v0.2.5
linter-js-yaml, v1.0.1
linter-puppet-lint, v0.2.9
linter-shellcheck, v0.0.7
markdown-scroll-sync, v0.3.4
notifications, v0.49.0
open-last-project, v0.4.1
pdf-view, v0.22.0
project-manager, v1.15.5
regex-railroad-diagram, v0.7.4
tabs-to-spaces, v0.10.0

# Dev
No dev packages
```

**Comment by Fank** [comment]
Will be fixed with #4
